### ISSUE TITLE
Ensure credentials are hidden in logs

### ISSUE THREAD

**Issue by razorcd** [razorcd/twilio-interface#1]
Twilio credentials sent from FE to controllers as params should not show in the app logs.

**Comment by razorcd** [comment]
Presence of credentials in log data is tested with RSpec now:
https://github.com/razorcd/twilio-interface/commit/79687bbd7108143ce25e5a093b4c768d8cd01ab4
https://github.com/razorcd/twilio-interface/commit/fdfbd6c1028a7a1a0d534889d891c8763b2e00c7
https://github.com/razorcd/twilio-interface/commit/294a3da8496e3f24e3004638620cccabddbd05df

**Comment by b264** [comment]
:+1:
